# my global config
global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 20s
    static_configs:
      - targets: [
        'host.docker.internal:9126',
        'host.docker.internal:2112',
      ]